// ============================================================
//  Generates sql/03_seed.sql from the settings registry + i18n
//  defaults. Run after editing settings.registry.js:
//      node scripts/gen-seed.js
// ============================================================
import { writeFileSync } from 'node:fs';
import { SETTINGS, TEXTS, EMOJI } from '../src/config/settings.registry.js';
import ar from '../src/i18n/locales/ar.js';
import en from '../src/i18n/locales/en.js';

const q = (s) => `'${String(s ?? '').replace(/'/g, "''")}'`;
const L = { ar, en };

let out = `-- ============================================================
--  03 — SEED   (GENERATED by scripts/gen-seed.js — do not edit by hand)
--
--  Every row uses ON CONFLICT DO NOTHING, so re-running never
--  overwrites values you changed from the admin panel.
--  Run after 01_schema.sql and 02_functions.sql.
-- ============================================================

-- ---------- settings (${Object.keys(SETTINGS).length}) ----------
insert into settings (key, value) values
`;
out += Object.entries(SETTINGS).map(([k, v]) => `  (${q(k)}, ${q(v.def)})`).join(',\n');
out += `\non conflict (key) do nothing;\n\n`;

out += `-- ---------- long texts (bilingual) ----------\ninsert into texts (key, content) values\n`;
const textRows = [];
for (const [key, meta] of Object.entries(TEXTS)) {
  if (meta.single) { textRows.push(`  (${q(key)}, '')`); continue; }
  for (const lang of ['ar', 'en']) {
    const def = L[lang][key]?.default ?? '';
    textRows.push(`  (${q(`${key}_${lang}`)}, ${q(def)})`);
  }
}
out += textRows.join(',\n') + `\non conflict (key) do nothing;\n\n`;

out += `-- ---------- ui emoji ----------\ninsert into ui_emoji (key, fallback) values\n`;
out += Object.entries(EMOJI).map(([k, v]) => `  (${q(k)}, ${q(v)})`).join(',\n');
out += `\non conflict (key) do nothing;\n\n`;

out += `-- ---------- loyalty tiers (only when table is empty) ----------
insert into tiers (name, emoji, min_spent, discount_pct, sort_order)
select * from (values
  ('مبتدئ · Starter', '🔰', 0,    0, 1),
  ('برونزي · Bronze', '🥉', 200,  1, 2),
  ('فضّي · Silver',   '🥈', 500,  2, 3),
  ('ذهبي · Gold',     '🥇', 1000, 3, 4),
  ('ماسي · Diamond',  '💎', 2500, 5, 5)
) as v(name, emoji, min_spent, discount_pct, sort_order)
where not exists (select 1 from tiers);

-- ---------- flat margin brackets (only when table is empty) ----------
--   cost < 15$ → +1.00$ · 15–25$ → +1.50$ · > 25$ → +2.00$
insert into margin_tiers (up_to, add_usd, sort_order)
select * from (values
  (14.99::numeric, 1.00::numeric, 1),
  (25.00::numeric, 1.50::numeric, 2),
  (null::numeric,  2.00::numeric, 3)
) as v(up_to, add_usd, sort_order)
where not exists (select 1 from margin_tiers);

-- ---------- sanity ----------
do $$
declare n int;
begin
  select count(*) into n from settings;
  raise notice 'settings rows: % (expected >= ${Object.keys(SETTINGS).length})', n;
  select count(*) into n from information_schema.routines
   where routine_schema = 'public' and routine_name in
   ('debit_and_open_order','complete_order','refund_order','credit_user','redeem_voucher',
    'open_withdrawal','reject_withdrawal','credit_payment','pay_referral_rewards');
  raise notice 'functions: % (expected 9)', n;
end $$;
`;

writeFileSync(new URL('../sql/03_seed.sql', import.meta.url), out);
console.log('✔ sql/03_seed.sql generated');
