-- ============================================================
--  03 — SEED   (GENERATED by scripts/gen-seed.js — do not edit by hand)
--
--  Every row uses ON CONFLICT DO NOTHING, so re-running never
--  overwrites values you changed from the admin panel.
--  Run after 01_schema.sql and 02_functions.sql.
-- ============================================================

-- ---------- settings (52) ----------
insert into settings (key, value) values
  ('margin_mode', 'flat'),
  ('markup_pct', '40'),
  ('flat_add_default', '1'),
  ('round_to', '0.25'),
  ('min_price', '0'),
  ('margin_after_discount', 'on'),
  ('min_margin_pct', '5'),
  ('min_margin_usd', '0.5'),
  ('auto_pause_on_loss', 'on'),
  ('price_move_alert_pct', '10'),
  ('referral_pct', '3'),
  ('ref_per_reward', '15'),
  ('ref_reward_usd', '1'),
  ('ref_daily_cap', '10'),
  ('ref_total_cap', '100'),
  ('ref_human_check', 'on'),
  ('pay_binance', 'on'),
  ('pay_cryptomus', 'on'),
  ('pay_stars', 'on'),
  ('deposit_min', '1'),
  ('deposit_max', '10000'),
  ('stars_rate', '0.009'),
  ('stars_packs', '50,100,250,500,1000'),
  ('stars_min', '50'),
  ('stars_max', '100000'),
  ('binance_session_min', '30'),
  ('cryptomus_lifetime_min', '60'),
  ('min_withdraw', '5'),
  ('premium_emoji', 'off'),
  ('button_colors', 'on'),
  ('show_stock_count', 'on'),
  ('products_per_page', '8'),
  ('notify_restock', 'on'),
  ('notify_new', 'on'),
  ('min_stock_delta', '1'),
  ('max_stock_alerts', '3'),
  ('alert_cooldown_min', '90'),
  ('low_wallet_alert', '20'),
  ('daily_report', 'on'),
  ('force_join', 'off'),
  ('join_channel_id', ''),
  ('join_channel_url', ''),
  ('join_group_id', ''),
  ('join_group_url', ''),
  ('maintenance', 'off'),
  ('support_user', ''),
  ('default_lang', 'ar'),
  ('sync_minutes', '10'),
  ('details_per_sync', '15'),
  ('details_refresh_hrs', '12'),
  ('health_check_min', '5'),
  ('recon_max_attempts', '6')
on conflict (key) do nothing;

-- ---------- long texts (bilingual) ----------
insert into texts (key, content) values
  ('welcome_ar', 'أهلاً فيك بمتجرنا 👋

اشتراكات رقمية بتسليم فوري وأسعار منافسة.
اختر من القائمة تحت للبدء.'),
  ('welcome_en', 'Welcome to our store 👋

Digital subscriptions with instant delivery and competitive prices.
Pick an option from the menu below to start.'),
  ('policy_ar', '<b>1. سياسة الاسترداد</b>
لا يمكن استرداد الأموال بعد الإيداع، إلا إذا أودعت ولم تشترِ أي منتج.

<b>2. سياسة الضمان</b>
نلتزم بضمان المنتجات المذكور فيها ضمان: استبدال فوري أو إرجاع المبلغ كرصيد.

<b>3. الأرصدة المجانية</b>
لا يمكن سحب الأموال الناتجة عن أكواد الشحن أو مكافآت الإحالة.'),
  ('policy_en', '<b>1. Refund policy</b>
Deposits are non-refundable unless you deposited and did not purchase anything.

<b>2. Warranty</b>
Products with a warranty are replaced immediately or refunded as balance.

<b>3. Free balance</b>
Balance from codes or referral rewards cannot be withdrawn.'),
  ('help_ar', '<b>الدعم والمساعدة</b>

إذا كنت تحتاج المساعدة، تواصل مع خدمة العملاء {user}.
سيتم الرد على طلبك في أقرب وقت.'),
  ('help_en', '<b>Help & support</b>

If you need help, contact our support {user}.
We will reply as soon as possible.'),
  ('binance_pay_id', '')
on conflict (key) do nothing;

-- ---------- ui emoji ----------
insert into ui_emoji (key, fallback) values
  ('shop', '🛒'),
  ('profile', '👤'),
  ('balance', '💰'),
  ('gift', '🎁'),
  ('card', '💳'),
  ('money', '💵'),
  ('help', '❓'),
  ('policy', '📜'),
  ('box', '📦'),
  ('clock', '⏳'),
  ('shield', '🛡'),
  ('check', '✅'),
  ('cross', '❌'),
  ('star', '⭐️'),
  ('receipt', '🧾'),
  ('admin', '⚙️'),
  ('bell', '🔔'),
  ('lang', '🌐')
on conflict (key) do nothing;

-- ---------- loyalty tiers (only when table is empty) ----------
insert into tiers (name, emoji, min_spent, discount_pct, sort_order)
select * from (values
  ('مبتدئ · Starter', '🔰', 0,    0, 1),
  ('برونزي · Bronze', '🥉', 200,  1, 2),
  ('فضّي · Silver',   '🥈', 500,  2, 3),
  ('ذهبي · Gold',     '🥇', 1000, 3, 4),
  ('ماسي · Diamond',  '💎', 2500, 5, 5)
) as v(name, emoji, min_spent, discount_pct, sort_order)
where not exists (select 1 from tiers);

-- ---------- flat margin brackets (only when table is empty) ----------
--   cost < 15$ → +1.00$ · 15–25$ → +1.50$ · > 25$ → +2.00$
insert into margin_tiers (up_to, add_usd, sort_order)
select * from (values
  (14.99::numeric, 1.00::numeric, 1),
  (25.00::numeric, 1.50::numeric, 2),
  (null::numeric,  2.00::numeric, 3)
) as v(up_to, add_usd, sort_order)
where not exists (select 1 from margin_tiers);

-- ---------- sanity ----------
do $$
declare n int;
begin
  select count(*) into n from settings;
  raise notice 'settings rows: % (expected >= 52)', n;
  select count(*) into n from information_schema.routines
   where routine_schema = 'public' and routine_name in
   ('debit_and_open_order','complete_order','refund_order','credit_user','redeem_voucher',
    'open_withdrawal','reject_withdrawal','credit_payment','pay_referral_rewards');
  raise notice 'functions: % (expected 9)', n;
end $$;
